[package]
name = "pfsense-modem-rebooter"
version = "0.1.0"
authors = ["Åke Amcoff <ake.amcoff@lynx.agency>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smartplug = "0.1"
clap = "2"